FROM 2.0.0-cuda11.8-ubuntu18.04:0.2

## Conda
# Install conda environment
RUN conda create -n py39torch200 python=3.9 -y

RUN bash -c "source activate py39torch200 && conda install -c anaconda pandas h5py ipython pyyaml pylint pillow setuptools -y"
RUN bash -c "source activate py39torch200 && conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia -y"
RUN bash -c "source activate py39torch200 && conda install -c conda-forge matplotlib librosa pudb tqdm ruamel.yaml jupyterlab sox cupy jupyterlab onnxruntime protobuf tensorboard -y"
RUN bash -c "source activate py39torch200 && conda install -c omnia termcolor -y"
RUN bash -c "source activate py39torch200 && pip install pesq"
RUN bash -c "source activate py39torch200 && pip install pystoi"
RUN bash -c "source activate py39torch200 && pip install PySoundFile"
RUN bash -c "source activate py39torch200 && pip install gpustat"
RUN bash -c "source activate py39torch200 && pip install pysndfx"
RUN bash -c "source activate py39torch200 && pip install thop"
RUN bash -c "source activate py39torch200 && pip install torchstat"
RUN bash -c "source activate py39torch200 && pip install ptflops"
RUN bash -c "source activate py39torch200 && pip install webrtcvad"
RUN bash -c "source activate py39torch200 && pip install nnAudio"
RUN bash -c "source activate py39torch200 && pip install learn2learn"

RUN bash -c "conda clean --all"